# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  repositories:
  - repository: repo1
    endpoint: anwar095
    trigger: none
    name: anwar095/JenkinsPipelines
    ref: 'refs/heads/main'
    type: github
  pipelines:
  - pipeline: pipeline1
    source: anwar095.java-repo    
    trigger:  none

trigger:
- none

pool:
  vmImage: ubuntu-latest
jobs:
- job: deploy_windows_x86_agent
  steps:
  - checkout: repo1
  - script: cat $(Pipeline.Workspace)/s/Dockerfile
    displayName: 'Run a one-line script'
  - download: pipeline1
    artifact: WebTier1
    patterns: '**/*.war'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'